// src/main/main.cpp — BeetleRecomp boot host
//
// Static-recompilation PC port of Beetle Adventure Racing (N64, USA).
// Adapted from Zelda64Recomp/Zelda64Recomp @ dev (src/main/main.cpp), but written against
// THIS repo's pinned runtime (lib/N64ModernRuntime @ main, ae1ffbb), whose recomp::start()
// takes a single recomp::Configuration struct. Every type/field below was verified against
// lib/N64ModernRuntime/{librecomp,ultramodern}/include headers.
//
// !!! UNTESTED — not yet compiled (no toolchain installed). The API *shape* matches the
// vendored headers, but callback BODIES are stubs and a few values are TODO. The game will
// not render until create_render_context (RT64) + the gfx/audio/input callbacks are
// implemented. The two MANDATORY callbacks (rsp_callbacks, renderer_callbacks) are wired so
// recomp::start()'s empty()-checks pass.

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>
#include <memory>
#include <filesystem>

#include "ultramodern/ultramodern.hpp"        // gfx_callbacks_t, audio_callbacks_t
#include "ultramodern/renderer_context.hpp"   // renderer::callbacks_t, RendererContext, WindowHandle
#include "ultramodern/error_handling.hpp"     // error_handling::callbacks_t
#include "ultramodern/events.hpp"             // events::callbacks_t (optional)
#include "ultramodern/input.hpp"              // input::callbacks_t
#include "ultramodern/threads.hpp"            // threads::callbacks_t

#include "librecomp/game.hpp"                 // recomp::{GameEntry,SaveType,Configuration,start,...}; pulls recomp.h
#include "librecomp/rsp.hpp"                  // recomp::rsp::callbacks_t, RspUcodeFunc, OSTask

// ----------------------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/ (externs only here).
// TODO(BAR): these exist only after `./N64Recomp BeetleRecomp.toml` runs on the recomp ELF.
// ----------------------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();   // generated; expected to resolve to BAR's entry VRAM 0x80000400

// RSP microcode entry point(s) generated by RSPRecomp.
// TODO(BAR): confirm BAR's stock audio ucode recompiles to `aspMain`. Graphics ucode (F3DEX2)
//            is handled by RT64 (HLE), so it is normally NOT recompiled here.
extern RspUcodeFunc aspMain;

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        case M_AUDTASK: return aspMain;
        // TODO(BAR): add cases (e.g. M_NJPEGTASK -> njpgdspMain) if BAR submits other RSP tasks.
        default:
            std::fprintf(stderr, "[BeetleRecomp] Unhandled RSP task type: %u\n", (unsigned)task->t.type);
            return nullptr;
    }
}

// ----------------------------------------------------------------------------------------
// Project metadata / game registration
// ----------------------------------------------------------------------------------------
static const std::string version_string = "0.1.0";   // TODO(BAR): real version string

// TODO(BAR): rom_hash is XXH3_64bits() of the byteswapped *z64* ROM — NOT the sha1.
//   Known USA sha1 = e5ab4d226c08d22f68a2edcc48870203e67454b8. Compute the XXH3-64 of the
//   validated z64 and paste it here (easiest: log XXH3_64bits() once during bring-up).
static constexpr uint64_t BAR_USA_ROM_XXH3 = 0x0000000000000000ULL;   // TODO: REPLACE

static std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash              = BAR_USA_ROM_XXH3,            // TODO(BAR)
        .internal_name         = "BEETLE ADVENTURE RACIN",   // TODO(BAR): exact name at ROM offset 0x20
        .game_id               = u8"bar.n64.us",             // stable id (arbitrary but fixed)
        .mod_game_id           = "bar",
        .save_type             = recomp::SaveType::None,      // BAR uses the Controller Pak (mempak), which
                                                             //   librecomp handles separately from SaveType.
        .is_enabled            = true,
        .decompression_routine = nullptr,                    // BAR code isn't compressed in the recomp output
        .has_compressed_code   = false,                      // TODO(BAR): verify vs your N64Recomp config
        .entrypoint_address    = get_entrypoint_address(),   // expected 0x80000400
        .entrypoint            = recomp_entrypoint,
    },
};

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// ----------------------------------------------------------------------------------------
// Port callback stubs. Signatures match the vendored headers; BODIES are TODO.
// ----------------------------------------------------------------------------------------

// RT64 renderer context (MANDATORY). Returning nullptr satisfies start()'s empty()-check
// (the callback pointer is non-null) but RT64 won't actually initialize until this is ported.
// TODO(BAR): port Zelda's src/main/rt64_render_context.cpp (subclass RendererContext, build
//            RT64::Application + app->setup()).
static std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* /*rdram*/, ultramodern::renderer::WindowHandle /*window_handle*/, bool /*developer_mode*/) {
    std::fprintf(stderr, "[BeetleRecomp] create_render_context: TODO (RT64 not wired)\n");
    return nullptr;
}

// SDL window / gfx (gfx_callbacks_t). TODO(BAR): SDL_CreateWindow titled "Beetle Adventure Racing".
static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() { return nullptr; }
static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) { return {}; }
static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) { /* TODO: pump SDL events */ }

// Audio (audio_callbacks_t). TODO(BAR): SDL audio device + sample ring buffer.
static void queue_samples(int16_t* /*samples*/, size_t /*count*/) {}
static size_t get_frames_remaining() { return 0; }
static void set_frequency(uint32_t /*freq*/) {}

// Input (input::callbacks_t). TODO(BAR): SDL controller -> N64 buttons/stick; Controller Pak info.
static void input_poll() {}
static bool input_get(int /*controller_num*/, uint16_t* /*buttons*/, float* /*x*/, float* /*y*/) { return false; }
static void input_set_rumble(int /*controller_num*/, bool /*rumble*/) {}

// Error handling (error_handling::callbacks_t).
static void message_box(const char* msg) { std::fprintf(stderr, "[BeetleRecomp] %s\n", msg); }

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    // TODO(BAR, optional): Win32 executable preload + timeBeginPeriod(1) for smoother frame times
    //                      (see Zelda's main.cpp). Omitted from this boot draft.

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        message_box(("Invalid version string: " + version_string).c_str());
        return EXIT_FAILURE;
    }

    // Config/save directory. TODO(BAR): use a proper per-user app folder, not cwd.
    recomp::register_config_path(std::filesystem::current_path());

    // Teach librecomp about BAR (hash / entrypoint / save type).
    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // TODO(BAR): bar::register_overlays(); bar::register_patches();  (generated overlay/patch tables)

    // ---- Assemble callbacks (field names verified against the vendored headers) ----
    recomp::rsp::callbacks_t rsp_callbacks{};                  // MANDATORY
    rsp_callbacks.get_rsp_microcode = get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};   // MANDATORY
    renderer_callbacks.create_render_context = create_render_context;

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input = input_poll;
    input_callbacks.get_input  = input_get;
    input_callbacks.set_rumble = input_set_rumble;
    // TODO(BAR): input_callbacks.get_connected_device_info (report Controller Pak / rumble pak).

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    recomp::Configuration config{};
    config.project_version          = project_version;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;
    // config.window_handle / events_callbacks / message_queue_control: defaults are fine for now.

    // Blocks until the game exits.
    recomp::start(config);
    return EXIT_SUCCESS;
}
