// src/main/main.cpp — BeetleRecomp boot host
//
// Static-recompilation PC port of Beetle Adventure Racing (N64, USA).
// Adapted from Zelda64Recomp/Zelda64Recomp @ dev (src/main/main.cpp), but written against
// THIS repo's pinned runtime (lib/N64ModernRuntime @ main, ae1ffbb), whose recomp::start()
// takes a single recomp::Configuration struct. Every type/field below was verified against
// lib/N64ModernRuntime/{librecomp,ultramodern}/include headers.
//
// Status (2026-06-28 night): boots deep. RT64 (D3D12) initializes, the SDL window opens, the ROM
// is recognized, libultra inits, and the uv module overlay bridge (src/main/overlay_bridge.cpp)
// registers relocatable modules as they load so recompiled module code runs. It currently crashes
// on module data-section relocation (a module data/.bss ref reads a garbage address). See
// docs/STATUS.md ("Next step: module data-section relocation").

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>
#include <memory>
#include <filesystem>
#include <thread>
#include <chrono>
#include <atomic>

#include "ultramodern/ultramodern.hpp"        // gfx_callbacks_t, audio_callbacks_t
#include "ultramodern/renderer_context.hpp"   // renderer::callbacks_t, RendererContext, WindowHandle
#include "ultramodern/error_handling.hpp"     // error_handling::callbacks_t
#include "ultramodern/events.hpp"             // events::callbacks_t (optional)
#include "ultramodern/input.hpp"              // input::callbacks_t
#include "ultramodern/threads.hpp"            // threads::callbacks_t

#include "librecomp/game.hpp"                 // recomp::{GameEntry,SaveType,Configuration,start,...}; pulls recomp.h
#include "librecomp/rsp.hpp"                  // recomp::rsp::callbacks_t, RspUcodeFunc, OSTask
#include "librecomp/overlays.hpp"             // overlay table (registration lives in register_overlays.cpp)

#include "game/config.hpp"                    // bar::config — settings persistence + high-FPS enable
#include "main/bar_cheats.h"                  // bar_cheats — BAR cheat toggles (host-side RDRAM pokes)

#ifdef BEETLE_ENABLE_UI
#include "ui/bar_ui.h"                        // bar_ui — RmlUi launcher + settings + cheats menu (Tier 2)
#endif

// The ROM the launcher's "Play" button loads (also the auto-start ROM when the UI is disabled).
// Set in main() before recomp::start() so the create_window callback can hand it to bar_ui.
static std::filesystem::path g_default_rom_path;

#define SDL_MAIN_HANDLED                      // we provide our own main()/entry; don't let SDL hijack it
#include <SDL.h>
#include <SDL_syswm.h>                        // SDL_GetWindowWMInfo -> native HWND
#ifdef _WIN32
#include <timeapi.h>                          // timeBeginPeriod (1ms timer resolution); links winmm
#endif

// ----------------------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/ (externs only here).
// TODO(BAR): these exist only after `./N64Recomp BeetleRecomp.toml` runs on the recomp ELF.
// ----------------------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();   // generated; expected to resolve to BAR's entry VRAM 0x80000400

// Wires the N64Recomp-generated section/overlay tables (recomp_overlays.inl) into librecomp.
// Defined in src/main/register_overlays.cpp.
void bar_register_overlays();

// RSP microcode entry points are generated by RSPRecomp. TODO(BAR): generate BAR's stock audio
// ucode (aspMain) with RSPRecomp and return it for M_AUDTASK. Graphics ucode (F3DEX2) is handled
// by RT64 (HLE), not recompiled here. Until the audio ucode exists, audio tasks are unhandled
// (the game may exit on the first one) — acceptable for the initial build/bring-up.
// No-op RSP ucode: BAR's audio ucode (aspMain) isn't generated by RSPRecomp yet. Reporting a normal
// RSP break makes run_task() treat the task as completed (silent) instead of fatally exiting the task
// thread. Graphics tasks (M_GFXTASK) never reach here — they go to the gfx thread's send_dl path.
static RspExitReason bar_rsp_ucode_stub(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
    return RspExitReason::Broke;
}

// BAR's stock audio microcode (aspMain), recompiled by RSPRecomp into rsp/aspMain.cpp. Generates the
// PCM for M_AUDTASK. ON by default; set BAR_NO_AUDIO to fall back to the silent stub (escape hatch in case
// the ucode hits an unhandled indirect-jump target on some task — BAR is libultra 2.0I vs reference 2.0J/L).
// Graphics ucode (F3DEX2) goes to RT64 (HLE), not here.
RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr);

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        case M_AUDTASK: {
            static const bool audio_off = std::getenv("BAR_NO_AUDIO") != nullptr;
            return audio_off ? bar_rsp_ucode_stub : aspMain;
        }
        default: {
            static bool warned = false;
            if (!warned) {
                std::fprintf(stderr, "[BeetleRecomp] RSP task type %u -> no-op stub\n",
                             (unsigned)task->t.type);
                warned = true;
            }
            return bar_rsp_ucode_stub;
        }
    }
}

// ----------------------------------------------------------------------------------------
// Project metadata / game registration
// ----------------------------------------------------------------------------------------
static const std::string version_string = "0.1.0";   // TODO(BAR): real version string

// TODO(BAR): rom_hash is XXH3_64bits() of the byteswapped *z64* ROM — NOT the sha1.
//   Known USA sha1 = e5ab4d226c08d22f68a2edcc48870203e67454b8. Compute the XXH3-64 of the
//   validated z64 and paste it here (easiest: log XXH3_64bits() once during bring-up).
static constexpr uint64_t BAR_USA_ROM_XXH3 = 0x56cfec69d7951f9fULL;   // XXH3_64 of the USA z64 (sha1 e5ab4d22…)

static std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash              = BAR_USA_ROM_XXH3,            // TODO(BAR)
        .internal_name         = "Beetle Adventure Rac",      // exact 20 bytes at ROM offset 0x20
        .game_id               = u8"bar.n64.us",             // stable id (arbitrary but fixed)
        .mod_game_id           = "bar",
        .save_type             = recomp::SaveType::None,      // BAR uses the Controller Pak (mempak), which
                                                             //   librecomp handles separately from SaveType.
        .is_enabled            = true,
        .decompression_routine = nullptr,                    // BAR code isn't compressed in the recomp output
        .has_compressed_code   = false,                      // TODO(BAR): verify vs your N64Recomp config
        .entrypoint_address    = get_entrypoint_address(),   // expected 0x80000400
        .entrypoint            = recomp_entrypoint,
    },
};

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// ----------------------------------------------------------------------------------------
// Port callback stubs. Signatures match the vendored headers; BODIES are TODO.
// ----------------------------------------------------------------------------------------

// RT64 renderer context (MANDATORY). Implemented in src/main/rt64_render_context.cpp.
std::unique_ptr<ultramodern::renderer::RendererContext>
bar_create_rt64_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode);

// Signals from rt64_render_context.cpp that gate the deferred start_game() below.
extern std::atomic<bool> g_bar_renderer_ready;   // RT64 finished setup
extern std::atomic<bool> g_bar_vi_ticked;        // renderer presented a frame (VI thread seeded a mode)

// SDL window / gfx (gfx_callbacks_t). RT64 attaches to this window's native HWND.
static SDL_Window* g_window = nullptr;
static HWND g_bar_hwnd = nullptr;   // native window handle (for keyboard focus gating)
static SDL_GameController* g_gamepad = nullptr;   // first connected SDL controller; touched ONLY on the main thread
static std::atomic<uint32_t> g_pad_state{0};      // packed pad snapshot: btn(bits0-15) | sx(16-23) | sy(24-31)

// Sample the connected SDL game controller into g_pad_state. MAIN THREAD ONLY (update_gfx) — keeping
// all SDL controller access + the g_gamepad handle on one thread avoids a disconnect-vs-read race with
// the game/SI threads that call bar_poll_gamepad. Mapping: A->A B->B Start->Start L/R shoulders->L/R
// LT->Z D-pad->D-pad right-stick->C-buttons left-stick->analog(±80). Rebind UI/profiles = TODO (item 6b).
static void bar_sample_gamepad() {
    SDL_GameController* gc = g_gamepad;
    if (gc == nullptr || !SDL_GameControllerGetAttached(gc)) { g_pad_state.store(0, std::memory_order_relaxed); return; }
    auto bdown = [gc](SDL_GameControllerButton b) { return SDL_GameControllerGetButton(gc, b) != 0; };
    uint16_t b = 0;
    if (bdown(SDL_CONTROLLER_BUTTON_A))             b |= 0x8000; // CONT_A
    if (bdown(SDL_CONTROLLER_BUTTON_B))             b |= 0x4000; // CONT_B
    if (bdown(SDL_CONTROLLER_BUTTON_START))         b |= 0x1000; // CONT_START
    if (bdown(SDL_CONTROLLER_BUTTON_LEFTSHOULDER))  b |= 0x0020; // CONT_L
    if (bdown(SDL_CONTROLLER_BUTTON_RIGHTSHOULDER)) b |= 0x0010; // CONT_R
    if (bdown(SDL_CONTROLLER_BUTTON_DPAD_UP))       b |= 0x0800;
    if (bdown(SDL_CONTROLLER_BUTTON_DPAD_DOWN))     b |= 0x0400;
    if (bdown(SDL_CONTROLLER_BUTTON_DPAD_LEFT))     b |= 0x0200;
    if (bdown(SDL_CONTROLLER_BUTTON_DPAD_RIGHT))    b |= 0x0100;
    if (SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_TRIGGERLEFT)  > 12000) b |= 0x2000; // Z trigger
    if (SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_TRIGGERRIGHT) > 12000) b |= 0x0010; // also R
    const int rx = SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_RIGHTX);
    const int ry = SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_RIGHTY);
    constexpr int kCDz = 16000;                  // C-buttons from the right analog stick
    if (ry < -kCDz) b |= 0x0008;                 // C-up
    if (ry >  kCDz) b |= 0x0004;                 // C-down
    if (rx < -kCDz) b |= 0x0002;                 // C-left
    if (rx >  kCDz) b |= 0x0001;                 // C-right
    const int lx = SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_LEFTX);
    const int ly = SDL_GameControllerGetAxis(gc, SDL_CONTROLLER_AXIS_LEFTY);
    constexpr int kDz = 8000;                    // left stick -> analog (±80), with a deadzone
    int nx = (lx > kDz || lx < -kDz) ? lx * 80 / 32767 : 0;
    int ny = (ly > kDz || ly < -kDz) ? -(ly * 80 / 32767) : 0;   // SDL Y down=+, N64 stick up=+
    if (nx >  80) nx =  80; else if (nx < -80) nx = -80;
    if (ny >  80) ny =  80; else if (ny < -80) ny = -80;
    g_pad_state.store((uint32_t)b | ((uint32_t)(uint8_t)(int8_t)nx << 16) | ((uint32_t)(uint8_t)(int8_t)ny << 24),
                      std::memory_order_relaxed);
}

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetMainReady();
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS | SDL_INIT_GAMECONTROLLER | SDL_INIT_AUDIO) != 0) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_Init failed: %s\n", SDL_GetError());
    }
    return nullptr;   // gfx_data_t is unused; the window is tracked in g_window
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
    g_window = SDL_CreateWindow("Beetle Adventure Racing: Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 960, 720,
        SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    if (g_window == nullptr) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_CreateWindow failed: %s\n", SDL_GetError());
        return {};
    }
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    if (SDL_GetWindowWMInfo(g_window, &wm_info) != SDL_TRUE) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_GetWindowWMInfo failed: %s\n", SDL_GetError());
        return {};
    }
    // create_window runs on the same (main) thread that pumps update_gfx below, so the
    // window's owning thread id is this thread.
    g_bar_hwnd = wm_info.info.win.window;

#ifdef BEETLE_ENABLE_UI
    // Register the RmlUi render hooks now, before the gfx thread constructs RT64 (recomp::start
    // calls create_window on this thread *before* spawning the gfx thread that runs
    // create_render_context → app->setup, which is when RT64 fires the UI init hook).
    bar_ui::install(g_window, g_default_rom_path);
#endif

    return ultramodern::renderer::WindowHandle{ wm_info.info.win.window, GetCurrentThreadId() };
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        if (event.type == SDL_QUIT) {
            ultramodern::quit();
            continue;
        }
        // Game controller hotplug. SDL queues a DEVICEADDED for controllers already present at init,
        // so this also picks up a controller plugged in before launch. We drive one controller (port 0).
        if (event.type == SDL_CONTROLLERDEVICEADDED) {
            if (g_gamepad == nullptr) {
                g_gamepad = SDL_GameControllerOpen(event.cdevice.which);
                if (g_gamepad != nullptr)
                    std::fprintf(stderr, "[BeetleRecomp] gamepad connected: %s\n", SDL_GameControllerName(g_gamepad));
            }
            continue;
        }
        if (event.type == SDL_CONTROLLERDEVICEREMOVED) {
            if (g_gamepad != nullptr &&
                event.cdevice.which == SDL_JoystickInstanceID(SDL_GameControllerGetJoystick(g_gamepad))) {
                SDL_GameControllerClose(g_gamepad);
                g_gamepad = nullptr;
                std::fprintf(stderr, "[BeetleRecomp] gamepad disconnected\n");
            }
            continue;
        }
#ifdef BEETLE_ENABLE_UI
        // Esc / F1 toggle the in-game pause menu (pauses the simulation; no effect pre-game — the
        // launcher is already up). The game never reads these keys (game input is GetAsyncKeyState /
        // controller based), so we consume them here.
        if (event.type == SDL_KEYDOWN && event.key.repeat == 0 &&
            (event.key.keysym.sym == SDLK_ESCAPE || event.key.keysym.sym == SDLK_F1)) {
            bar_ui::toggle_pause_menu();
            continue;
        }
        // Controller Back/View/Select button also toggles the pause menu (N64 pads have no such
        // button, so it never conflicts with game input).
        if (event.type == SDL_CONTROLLERBUTTONDOWN && event.cbutton.button == SDL_CONTROLLER_BUTTON_BACK) {
            bar_ui::toggle_pause_menu();
            continue;
        }
        // Controller navigation of the menu: translate buttons to the keyboard nav the menu already
        // handles (D-pad -> arrows = move focus; A -> Enter = activate). Synthesize a key event and feed
        // it through the same path. Only while the menu owns input.
        if (bar_ui::menu_capturing_input() && event.type == SDL_CONTROLLERBUTTONDOWN) {
            SDL_Keycode key = 0;
            switch (event.cbutton.button) {
                case SDL_CONTROLLER_BUTTON_DPAD_UP:    key = SDLK_UP;     break;
                case SDL_CONTROLLER_BUTTON_DPAD_DOWN:  key = SDLK_DOWN;   break;
                case SDL_CONTROLLER_BUTTON_DPAD_LEFT:  key = SDLK_LEFT;   break;
                case SDL_CONTROLLER_BUTTON_DPAD_RIGHT: key = SDLK_RIGHT;  break;
                case SDL_CONTROLLER_BUTTON_A:          key = SDLK_RETURN; break;
                default: break;
            }
            if (key != 0) {
                SDL_Event k{};
                k.type = SDL_KEYDOWN;
                k.key.type = SDL_KEYDOWN;
                k.key.state = SDL_PRESSED;
                k.key.repeat = 0;
                k.key.keysym.sym = key;
                k.key.keysym.scancode = SDL_GetScancodeFromKey(key);
                bar_ui::handle_sdl_event(k);
            }
            continue;
        }
        // While the launcher/settings/cheats menu owns input, forward events to RmlUi (drained on
        // the render thread). Once the game starts, the menu hides and input goes to the game.
        if (bar_ui::menu_capturing_input()) {
            bar_ui::handle_sdl_event(event);
        }
#endif
    }
    bar_sample_gamepad();   // refresh the controller snapshot on this (main) thread
}

// Audio (audio_callbacks_t) — SDL2 queued-audio backend.
// The libultra->ultramodern AI chain (librecomp/src/ai.cpp -> ultramodern/src/audio.cpp) delivers the
// game's PCM here as `count` interleaved-stereo int16 samples pointing straight into RDRAM (no swap done
// upstream). EMPIRICALLY VERIFIED (captured BAR menu music, offline autocorrelation): the raw int16
// values are ALREADY correct host-order (librecomp's RDRAM word-swizzle yields correct s16 on raw read);
// byteswapping them produces white-noise "screeching". The word-swizzle delivers the pair as [R,L], so
// we channel-swap to [L,R] (matches Zelda64Recompiled's backend). BAR_AUDIO_XFORM overrides:
//   0 = as-is, 1 = byteswap only, 2 = channel-swap only [default, correct], 3 = byteswap + channel-swap.
//
// SAFETY: the output device is opened (and sound produced) ONLY when BAR_AUDIO_PLAY is set. By default —
// and while verifying correctness — NO device is opened and NOTHING plays. BAR_AUDIO_CAPTURE=<path> dumps
// the raw (untransformed) received stream so the correct transform can be checked offline without audio.
static SDL_AudioDeviceID g_audio_dev = 0;
static uint32_t g_dev_freq  = 0;        // freq the SDL device is currently open at
static uint32_t g_game_freq = 0;        // last freq the game requested (for capture/WAV)
static constexpr int kBarBytesPerFrame = 2 * (int)sizeof(int16_t);   // stereo s16
static std::FILE* g_audio_capture = nullptr;
static size_t g_audio_capture_bytes = 0;

static bool bar_audio_play_enabled() {
    // Audio output ON by default; BAR_NO_AUDIO disables the device (and the ucode, see get_rsp_microcode).
    static const bool on = std::getenv("BAR_NO_AUDIO") == nullptr;
    return on;
}
static int bar_audio_xform() {
    static const int x = []{ const char* e = std::getenv("BAR_AUDIO_XFORM"); return e ? std::atoi(e) : 2; }();
    return x;
}

static void bar_open_audio(uint32_t freq) {
    if (freq == 0) return;
    g_game_freq = freq;
    if (g_audio_capture == nullptr) {
        static bool tried = false;
        if (!tried) { tried = true;
            const char* cap = std::getenv("BAR_AUDIO_CAPTURE");
            if (cap && *cap) { g_audio_capture = std::fopen(cap, "wb");
                std::fprintf(stderr, "[BeetleRecomp] audio capture -> %s\n", cap); }
        }
    }
    if (!bar_audio_play_enabled()) return;          // muted: never open a device, never play
    if (g_audio_dev != 0 && g_dev_freq == freq) return;
    if (g_audio_dev != 0) { SDL_CloseAudioDevice(g_audio_dev); g_audio_dev = 0; }
    if (SDL_WasInit(SDL_INIT_AUDIO) == 0 && SDL_InitSubSystem(SDL_INIT_AUDIO) != 0) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_InitSubSystem(AUDIO) failed: %s\n", SDL_GetError());
        return;
    }
    SDL_AudioSpec want{}, have{};
    want.freq = (int)freq; want.format = AUDIO_S16SYS; want.channels = 2; want.samples = 1024; want.callback = nullptr;
    g_audio_dev = SDL_OpenAudioDevice(nullptr, 0, &want, &have, 0);
    if (g_audio_dev == 0) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_OpenAudioDevice failed: %s\n", SDL_GetError());
        return;
    }
    g_dev_freq = (uint32_t)have.freq;
    SDL_PauseAudioDevice(g_audio_dev, 0);
}

static void queue_samples(int16_t* samples, size_t count) {
    if (samples == nullptr || count == 0) return;
    // Capture the RAW received stream (no transform) for offline analysis, capped at ~16 MB.
    if (g_audio_capture && g_audio_capture_bytes < (16u << 20)) {
        size_t n = std::fwrite(samples, sizeof(int16_t), count, g_audio_capture);
        g_audio_capture_bytes += n * sizeof(int16_t);
    }
    if (g_audio_dev == 0) return;                    // muted (default) — produce no sound
    const int xf = bar_audio_xform();
    const bool byteswap = (xf == 1 || xf == 3);
    const bool chanswap = (xf == 2 || xf == 3);
    static std::vector<int16_t> out;
    out.resize(count);
    for (size_t i = 0; i < count; i++) {
        uint16_t v = (uint16_t)samples[i];
        out[i] = byteswap ? (int16_t)(uint16_t)((v >> 8) | (v << 8)) : (int16_t)v;
    }
    if (chanswap) { for (size_t i = 0; i + 1 < count; i += 2) { int16_t t = out[i]; out[i] = out[i+1]; out[i+1] = t; } }
    { static const bool dbg = std::getenv("BAR_AUDIO_DBG") != nullptr; if (dbg) {
        extern int g_bar_audio_peak; extern long g_bar_audio_clip;
        for (size_t i = 0; i < count; i++) { int a = out[i] < 0 ? -(int)out[i] : out[i];
            if (a > g_bar_audio_peak) g_bar_audio_peak = a; if (a >= 32760) g_bar_audio_clip++; } } }
    SDL_QueueAudio(g_audio_dev, out.data(), (Uint32)(count * sizeof(int16_t)));
}

int  g_bar_audio_peak = 0;   // diag (BAR_AUDIO_DBG): peak |sample| + saturation count
long g_bar_audio_clip = 0;

static size_t get_frames_remaining() {
    if (g_audio_dev == 0) return 0;
    size_t frames = (size_t)(SDL_GetQueuedAudioSize(g_audio_dev) / (Uint32)kBarBytesPerFrame);
    { static const bool dbg = std::getenv("BAR_AUDIO_DBG") != nullptr; if (dbg) {
        // Inter-call wall delta (called ~once per game frame). Flag genuine near-underruns (queue almost
        // empty) and egregious single-frame stalls (>50 ms = >3 VI) — not normal 16.6 ms frames.
        static auto last = std::chrono::steady_clock::now(); auto now = std::chrono::steady_clock::now();
        double dms = std::chrono::duration<double, std::milli>(now - last).count(); last = now;
        if ((frames < 150 && frames > 0) || dms > 50.0) { std::fprintf(stderr, "[BeetleRecomp] audio LOW: queued=%zu frameDelta=%.1fms\n", frames, dms); std::fflush(stderr); }
        static size_t minq = (size_t)-1, maxq = 0; static int n = 0;
        if (frames < minq) minq = frames; if (frames > maxq) maxq = frames;
        if ((++n % 60) == 0) {
            std::fprintf(stderr, "[BeetleRecomp] audio: queued now=%zu min=%zu max=%zu | peak=%d clipped=%ld%s\n",
                         frames, minq, maxq, g_bar_audio_peak, g_bar_audio_clip,
                         (minq == 0) ? "  <<< UNDERRUN" : "");
            std::fflush(stderr); minq = (size_t)-1; maxq = 0; g_bar_audio_peak = 0; g_bar_audio_clip = 0;
        } } }
    return frames;
}

static void set_frequency(uint32_t freq) {
    if (freq != 0 && freq != g_dev_freq) bar_open_audio(freq);
}

// Input (input::callbacks_t). Port 0 is reported connected; the live pad state comes from
// bar_poll_keyboard (keyboard + SDL game controller, see bar_poll_gamepad). TODO(BAR): a rebind UI
// (item 6b) + per-controller profiles.
static void input_poll() {
}

// bar_poll_keyboard (defined below) is the single input source — BAR_AUTOPLAY script or live
// keyboard. It feeds BOTH the high-level path (this callback, for ultramodern's osContGetReadData)
// and the low-level SI path (os_unimpl_stubs.cpp's __osSiRawStartDma fill), so input reaches the
// game whichever way it polls.
extern "C" uint16_t bar_poll_keyboard(int port, int8_t* stick_x, int8_t* stick_y);

static bool input_get(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (controller_num != 0) {
        return false;   // only port 1 is "connected"
    }
    int8_t sx = 0, sy = 0;
    const uint16_t b = bar_poll_keyboard(0, &sx, &sy);
    if (buttons != nullptr) *buttons = b;
    if (x != nullptr)       *x = (float)sx / 80.0f;   // N64 stick range -> ~[-1, 1]
    if (y != nullptr)       *y = (float)sy / 80.0f;
    return true;
}

static void input_set_rumble(int /*controller_num*/, bool /*rumble*/) {}

static ultramodern::input::connected_device_info_t input_get_device_info(int controller_num) {
    using namespace ultramodern::input;
    if (controller_num == 0) {
        return connected_device_info_t{ Device::Controller, Pak::None };
    }
    return connected_device_info_t{ Device::None, Pak::None };
}

// Keyboard -> N64 controller (port 0). BAR reads the pad via the raw SI/PIF path, so
// __osSiRawStartDma_recomp (os_unimpl_stubs.cpp) calls this to fill the read buffer. Uses Win32 async
// key state, gated to when the game window is focused. Bindings (port 0):
//   Analog stick: Arrows   A: X   B: Z   Start: Enter   Z-trigger: Shift   L: Q   R: W   C-buttons: I/J/K/L   D-pad: T/F/G/H
// Scripted auto-input for headless menu/race testing. Set BAR_AUTOPLAY to a space-separated
// sequence of "frames:hexbuttons" phases, played in order then held neutral. Hex is the N64 button
// mask (START=1000 A=8000 B=4000 Z=2000; d-pad U=0800 D=0400 L=0200 R=0100). D-pad bits also drive
// the analog stick so menus reading either respond. Bypasses the focus gate.
// Example: BAR_AUTOPLAY="180:0 12:1000 60:0 12:8000"  -> wait, tap START, wait, tap A.
static uint16_t bar_autoplay_poll(const char* script, int8_t* stick_x, int8_t* stick_y) {
    struct Phase { int dur; uint16_t btn; };
    static std::vector<Phase> phases;
    static bool parsed = false;
    static size_t idx = 0;
    static int held = 0;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        for (const char* p = script; *p; ) {
            while (*p == ' ' || *p == '\t') ++p;
            if (!*p) break;
            char* e = nullptr;
            long dur = std::strtol(p, &e, 10);
            uint16_t btn = 0;
            if (e && *e == ':') btn = (uint16_t)std::strtol(e + 1, &e, 16);
            p = (e && e != p) ? e : p + 1;
            if (dur > 0) phases.push_back({(int)dur, btn});
        }
        std::fprintf(stderr, "[BeetleRecomp] AUTOPLAY: %zu phases parsed\n", phases.size());
        std::fflush(stderr);
    }
    ++fc;
    uint16_t btn = 0;
    if (idx < phases.size()) {
        btn = phases[idx].btn;
        if (++held >= phases[idx].dur) {
            held = 0; ++idx;
            std::fprintf(stderr, "[BeetleRecomp] AUTOPLAY -> phase %zu/%zu @fc=%llu next=0x%04X\n",
                         idx, phases.size(), fc, (unsigned)(idx < phases.size() ? phases[idx].btn : 0));
            std::fflush(stderr);
        }
    }
    int sx = 0, sy = 0;
    if (btn & 0x0800) sy += 80;
    if (btn & 0x0400) sy -= 80;
    if (btn & 0x0200) sx -= 80;
    if (btn & 0x0100) sx += 80;
    if (stick_x) *stick_x = (int8_t)sx;
    if (stick_y) *stick_y = (int8_t)sy;
    return btn;
}

// Fold the latest controller snapshot (sampled on the main thread by bar_sample_gamepad) into the pad
// state: OR the buttons, and use the controller's left stick only if the keyboard left it neutral.
static void bar_poll_gamepad(uint16_t* btn, int* sx, int* sy) {
    const uint32_t s = g_pad_state.load(std::memory_order_relaxed);
    *btn |= (uint16_t)(s & 0xFFFF);
    if (*sx == 0 && *sy == 0) {
        *sx = (int)(int8_t)((s >> 16) & 0xFF);
        *sy = (int)(int8_t)((s >> 24) & 0xFF);
    }
}

// BAR_SHOTS="frame:path frame:path ..." — request an internal-render screenshot (RT64 GPU readback -> PNG)
// at each listed frame, on the SAME frame counter as BAR_AUTOPLAY so captures line up with scripted input.
extern "C" void bar_rt64_request_screenshot(const char *path);
static void bar_shots_poll() {
    struct Shot { unsigned long frame; std::string path; };
    static std::vector<Shot> shots;
    static bool parsed = false;
    static size_t idx = 0;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        if (const char *s = std::getenv("BAR_SHOTS")) {
            for (const char *p = s; *p; ) {
                while (*p == ' ' || *p == '\t') ++p;
                if (!*p) break;
                char *e = nullptr;
                long fr = std::strtol(p, &e, 10);
                if (e && *e == ':') {
                    const char *ps = e + 1, *pe = ps;
                    while (*pe && *pe != ' ' && *pe != '\t') ++pe;
                    if (fr > 0 && pe > ps) shots.push_back({ (unsigned long)fr, std::string(ps, pe - ps) });
                    p = pe;
                } else {
                    p = (e && e != p) ? e : p + 1;
                }
            }
            std::fprintf(stderr, "[BeetleRecomp] BAR_SHOTS: %zu scheduled\n", shots.size());
        }
    }
    ++fc;
    while (idx < shots.size() && fc >= shots[idx].frame) {
        bar_rt64_request_screenshot(shots[idx].path.c_str());
        std::fprintf(stderr, "[BeetleRecomp] BAR_SHOTS -> %s @fc=%llu\n", shots[idx].path.c_str(), (unsigned long long)fc);
        ++idx;
    }
}

// BAR_SHOT_BURST="fc:dir:count" — at input frame fc, tell RT64 to capture the next `count` presents to
// dir/fNNNN.png (one per present). For animations the input timeline can't sample (film-roll transition:
// the game blocks in a render loop and stops polling input, so BAR_SHOTS frames freeze mid-roll). Trigger
// a few frames BEFORE the transition, while fc is still advancing; RT64 then counts presents on its own.
extern "C" void bar_rt64_start_burst(const char *dir, int count);
static void bar_burst_poll() {
    static bool parsed = false, fired = false;
    static unsigned long fc_trigger = 0; static int count = 0; static std::string dir;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        if (const char *s = std::getenv("BAR_SHOT_BURST")) {
            std::string spec(s);
            size_t c1 = spec.find(':'), c2 = (c1 == std::string::npos) ? std::string::npos : spec.find(':', c1 + 1);
            if (c2 != std::string::npos) {
                fc_trigger = std::strtoul(spec.substr(0, c1).c_str(), nullptr, 10);
                dir = spec.substr(c1 + 1, c2 - c1 - 1);
                count = std::atoi(spec.substr(c2 + 1).c_str());
            }
            std::fprintf(stderr, "[BeetleRecomp] BAR_SHOT_BURST: fc=%lu dir=%s count=%d\n", fc_trigger, dir.c_str(), count);
        }
    }
    ++fc;
    if (!fired && count > 0 && fc >= fc_trigger) {
        fired = true;
        bar_rt64_start_burst(dir.c_str(), count);
        std::fprintf(stderr, "[BeetleRecomp] BAR_SHOT_BURST triggered @fc=%llu\n", (unsigned long long)fc);
        std::fflush(stderr);
    }
}

extern "C" uint16_t bar_poll_keyboard(int port, int8_t* stick_x, int8_t* stick_y) {
    if (stick_x) *stick_x = 0;
    if (stick_y) *stick_y = 0;
    if (port != 0) return 0;
    bar_shots_poll();
    bar_burst_poll();
    static const char* autoplay = std::getenv("BAR_AUTOPLAY");
    if (autoplay && *autoplay) return bar_autoplay_poll(autoplay, stick_x, stick_y);
#ifdef BEETLE_ENABLE_UI
    // While the cheats/settings overlay is open, freeze game input so menu navigation (arrows/enter)
    // doesn't also drive the car.
    if (bar_ui::menu_capturing_input()) return 0;
#endif
    if (g_bar_hwnd != nullptr && GetForegroundWindow() != g_bar_hwnd) return 0; // only when focused
    auto down = [](int vk) { return (GetAsyncKeyState(vk) & 0x8000) != 0; };
    uint16_t b = 0;
    if (down('X'))       b |= 0x8000; // CONT_A
    if (down('Z'))       b |= 0x4000; // CONT_B
    if (down(VK_SHIFT))  b |= 0x2000; // CONT_G (Z trigger)
    if (down(VK_RETURN)) b |= 0x1000; // CONT_START
    if (down('T'))       b |= 0x0800; // D-pad up
    if (down('G'))       b |= 0x0400; // D-pad down
    if (down('F'))       b |= 0x0200; // D-pad left
    if (down('H'))       b |= 0x0100; // D-pad right
    if (down('Q'))       b |= 0x0020; // CONT_L
    if (down('W'))       b |= 0x0010; // CONT_R
    if (down('I'))       b |= 0x0008; // C-up
    if (down('K'))       b |= 0x0004; // C-down
    if (down('J'))       b |= 0x0002; // C-left
    if (down('L'))       b |= 0x0001; // C-right
    int sx = 0, sy = 0;
    if (down(VK_LEFT))  sx -= 80;
    if (down(VK_RIGHT)) sx += 80;
    if (down(VK_UP))    sy += 80;   // N64 stick: up is positive
    if (down(VK_DOWN))  sy -= 80;
    bar_poll_gamepad(&b, &sx, &sy);   // fold in an SDL game controller if one is connected
    if (stick_x) *stick_x = (int8_t)sx;
    if (stick_y) *stick_y = (int8_t)sy;
    return b;
}

// Error handling (error_handling::callbacks_t).
static void message_box(const char* msg) { std::fprintf(stderr, "[BeetleRecomp] %s\n", msg); }

// "Restart Game" (pause menu): the recompiled game can't be cleanly re-entered in-process, so restart
// the whole process — relaunch the exe with the same arguments, then quit this instance. Declared in
// src/ui/bar_ui.cpp. Non-static so the UI TU can link to it.
void bar_restart_game() {
#ifdef _WIN32
    char exe[MAX_PATH] = {};
    GetModuleFileNameA(nullptr, exe, MAX_PATH);
    std::string cmd = GetCommandLineA();   // relaunch with the same args (ROM path, etc.) + same cwd
    STARTUPINFOA si{}; si.cb = sizeof(si);
    PROCESS_INFORMATION pi{};
    if (CreateProcessA(exe, cmd.empty() ? nullptr : cmd.data(), nullptr, nullptr, FALSE, 0,
                       nullptr, nullptr, &si, &pi)) {
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    } else {
        std::fprintf(stderr, "[BeetleRecomp] restart: CreateProcess failed (%lu)\n", (unsigned long)GetLastError());
    }
#endif
    ultramodern::quit();   // exit this instance (the fresh one takes over)
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
#ifdef _WIN32
    { extern void bar_install_crash_handler(); bar_install_crash_handler(); }   // symbolized backtrace on AV
#endif
#ifdef _WIN32
    // Raise the Windows timer resolution to 1ms. CRITICAL for menu/sparse-workload framerate: the game's
    // VI-synced RCP scheduler + our runtime's gfx/task threads hand work off via timed waits. At the default
    // ~15.6ms timer resolution, each wake quantizes to ~15.6ms, so a single gfx round-trip costs ~2 quanta
    // (~32ms) and a menu frame several — capping the menu at ~10fps. (A race never waits — it always has gfx
    // queued — so it was unaffected and this was wrongly dismissed as "jitter only".) winmm is linked.
    if (std::getenv("BAR_NO_TIMER_FIX") == nullptr) timeBeginPeriod(1);  // R6 bisect: BAR_NO_TIMER_FIX=1 reverts this menu-FPS fix
#endif

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        message_box(("Invalid version string: " + version_string).c_str());
        return EXIT_FAILURE;
    }

    // Config/save directory: a real per-user folder (%LOCALAPPDATA%\BeetleRecomp on Windows;
    // ~/.config/BeetleRecomp on Linux), or the exe dir when a portable.txt is present. librecomp
    // writes saves / mod config here.
    recomp::register_config_path(bar::config::get_app_config_directory());

    // Load persisted graphics settings (or write defaults on first run) and push them into the
    // runtime. This also enables RT64 high-FPS frame interpolation: the default config sets
    // rr_option = Display, so presentation tracks the monitor refresh while the game/VI/audio
    // clock stays locked at its native 60 Hz (identical game speed — see
    // docs/SETTINGS_MENU_AND_HIGH_FPS.md). Must run before recomp::start() so the renderer reads
    // it when it constructs the RT64 context.
    bar::config::load_and_apply_graphics();

    // Load persisted cheat toggles (applied per-frame from the SI hook once the game runs; also
    // editable live via the in-game cheats menu — F1).
    bar_cheats::load();

    // Teach librecomp about BAR (hash / entrypoint / save type).
    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // Wire the generated section/overlay tables so BAR's ~130 relocatable modules resolve at runtime.
    bar_register_overlays();
    // TODO(BAR): bar::register_patches(); once patches exist.

    // ---- ROM source ----
    // The launcher's "Play" button loads this ROM; with the UI disabled it's the auto-start ROM.
    g_default_rom_path = (argc > 1)
        ? std::filesystem::path(argv[1])
        : std::filesystem::path("C:/Users/Bryan/Downloads/Beetle Adventure Racing (USA).z64"); // TODO(BAR): native ROM picker

    std::u8string game_id = supported_games[0].game_id;

    // Coordinator: the game thread blocks in wait_for_game_started() until start_game() runs. The VI
    // thread only seeds a dummy OSViMode while !is_game_started(); starting before its first tick
    // makes update_vi() deref a null mode — so we wait for g_bar_vi_ticked (renderer presented a
    // frame, which also means the launcher can draw over it). recomp::start() below blocks the main
    // thread, so this runs on a detached thread.
    std::thread([game_id]() mutable {   // mutable: recomp::select_rom takes a non-const std::u8string&
        using namespace std::chrono_literals;
        for (int i = 0; i < 500 && !g_bar_vi_ticked.load(); i++) {
            std::this_thread::sleep_for(10ms);
        }

        std::filesystem::path rom = g_default_rom_path;
        // Start the game right away — do NOT wait for "Play". The launcher/settings/cheats menu is an
        // OVERLAY drawn over the running game: RT64 only drives the UI's render+input render-hook while
        // the game is producing frames, so the menu cannot be interactive before the game starts. The
        // launcher stays shown over the (booting) game until the user clicks Play (which hides it);
        // F1 reopens the menu in-game. BAR_SKIP_LAUNCHER starts with the overlay hidden (headless).

        recomp::RomValidationError rom_err = recomp::select_rom(rom, game_id);
        if (rom_err != recomp::RomValidationError::Good) {
            message_box(("Could not load ROM \"" + rom.string() + "\" (validation error "
                         + std::to_string(static_cast<int>(rom_err)) + ")").c_str());
            return;
        }
        recomp::start_game(game_id);
#ifdef BEETLE_ENABLE_UI
        bar_ui::on_game_started();   // mark game started (enables F1); the launcher stays as an overlay
#endif
    }).detach();

    // ---- Assemble callbacks (field names verified against the vendored headers) ----
    recomp::rsp::callbacks_t rsp_callbacks{};                  // MANDATORY
    rsp_callbacks.get_rsp_microcode = get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};   // MANDATORY
    renderer_callbacks.create_render_context = bar_create_rt64_render_context;

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input = input_poll;
    input_callbacks.get_input  = input_get;
    input_callbacks.set_rumble = input_set_rumble;
    input_callbacks.get_connected_device_info = input_get_device_info;

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    recomp::Configuration config{};
    config.project_version          = project_version;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;
    // MENU-FPS FIX: BAR's SI (controller) event queue (main.c:311, D_8002F828) is only capacity 3, and our
    // low-level __osSiRawStartDma stub posts an SI completion per call. BAR doesn't drain them all during
    // the menu, so the queue fills with stale completions; with the default requeue_si=true, every new SI
    // completion then BOUNCES (re-queues) off the full queue in a ~15M/sec busy-spin that starves the
    // cooperative scheduler and throttled the menu to ~10fps. SI completions are disposable (live input is
    // re-read from PIF RAM each frame), so drop the excess instead of bouncing it.
    config.message_queue_control.requeue_si = (std::getenv("BAR_REQUEUE_SI") != nullptr);  // R6 bisect: default false (the menu-FPS fix); BAR_REQUEUE_SI=1 reverts to stock true
    // config.window_handle / events_callbacks: defaults are fine for now.

    // Cooperative audio-thread preemption: raise a host "yield now" flag at ~500Hz; a poll injected at every
    // recompiled-function prologue (fix-recompiled.sh rule F) then yields to the audio manager so long
    // straight-line game-thread compute can't starve audio (-> no underrun crackle at a low buffer). The flag
    // is gated to game threads once running, so starting the timer before the game spins up is harmless.
    extern void bar_start_preempt_timer();
    extern void bar_stop_preempt_timer();
    bar_start_preempt_timer();

    // Blocks until the game exits.
    recomp::start(config);
    bar_stop_preempt_timer();
    return EXIT_SUCCESS;
}
