// src/main/main.cpp — BeetleRecomp boot host
//
// Static-recompilation PC port of Beetle Adventure Racing (N64, USA).
// Adapted from Zelda64Recomp/Zelda64Recomp @ dev (src/main/main.cpp), but written against
// THIS repo's pinned runtime (lib/N64ModernRuntime @ main, ae1ffbb), whose recomp::start()
// takes a single recomp::Configuration struct. Every type/field below was verified against
// lib/N64ModernRuntime/{librecomp,ultramodern}/include headers.
//
// Status (2026-06-28 night): boots deep. RT64 (D3D12) initializes, the SDL window opens, the ROM
// is recognized, libultra inits, and the uv module overlay bridge (src/main/overlay_bridge.cpp)
// registers relocatable modules as they load so recompiled module code runs. It currently crashes
// on module data-section relocation (a module data/.bss ref reads a garbage address). See
// docs/STATUS.md ("Next step: module data-section relocation").

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>
#include <memory>
#include <filesystem>
#include <thread>
#include <chrono>
#include <atomic>

#include "ultramodern/ultramodern.hpp"        // gfx_callbacks_t, audio_callbacks_t
#include "ultramodern/renderer_context.hpp"   // renderer::callbacks_t, RendererContext, WindowHandle
#include "ultramodern/error_handling.hpp"     // error_handling::callbacks_t
#include "ultramodern/events.hpp"             // events::callbacks_t (optional)
#include "ultramodern/input.hpp"              // input::callbacks_t
#include "ultramodern/threads.hpp"            // threads::callbacks_t

#include "librecomp/game.hpp"                 // recomp::{GameEntry,SaveType,Configuration,start,...}; pulls recomp.h
#include "librecomp/rsp.hpp"                  // recomp::rsp::callbacks_t, RspUcodeFunc, OSTask
#include "librecomp/overlays.hpp"             // overlay table (registration lives in register_overlays.cpp)

#define SDL_MAIN_HANDLED                      // we provide our own main()/entry; don't let SDL hijack it
#include <SDL.h>
#include <SDL_syswm.h>                        // SDL_GetWindowWMInfo -> native HWND

// ----------------------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/ (externs only here).
// TODO(BAR): these exist only after `./N64Recomp BeetleRecomp.toml` runs on the recomp ELF.
// ----------------------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();   // generated; expected to resolve to BAR's entry VRAM 0x80000400

// Wires the N64Recomp-generated section/overlay tables (recomp_overlays.inl) into librecomp.
// Defined in src/main/register_overlays.cpp.
void bar_register_overlays();

// RSP microcode entry points are generated by RSPRecomp. TODO(BAR): generate BAR's stock audio
// ucode (aspMain) with RSPRecomp and return it for M_AUDTASK. Graphics ucode (F3DEX2) is handled
// by RT64 (HLE), not recompiled here. Until the audio ucode exists, audio tasks are unhandled
// (the game may exit on the first one) — acceptable for the initial build/bring-up.
// No-op RSP ucode: BAR's audio ucode (aspMain) isn't generated by RSPRecomp yet. Reporting a normal
// RSP break makes run_task() treat the task as completed (silent) instead of fatally exiting the task
// thread. Graphics tasks (M_GFXTASK) never reach here — they go to the gfx thread's send_dl path.
static RspExitReason bar_rsp_ucode_stub(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
    return RspExitReason::Broke;
}

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        // case M_AUDTASK: return aspMain;   // TODO(BAR): wire RSPRecomp audio ucode output here
        default: {
            static bool warned = false;
            if (!warned) {
                std::fprintf(stderr, "[BeetleRecomp] RSP task type %u -> no-op stub (audio not wired yet)\n",
                             (unsigned)task->t.type);
                warned = true;
            }
            return bar_rsp_ucode_stub;
        }
    }
}

// ----------------------------------------------------------------------------------------
// Project metadata / game registration
// ----------------------------------------------------------------------------------------
static const std::string version_string = "0.1.0";   // TODO(BAR): real version string

// TODO(BAR): rom_hash is XXH3_64bits() of the byteswapped *z64* ROM — NOT the sha1.
//   Known USA sha1 = e5ab4d226c08d22f68a2edcc48870203e67454b8. Compute the XXH3-64 of the
//   validated z64 and paste it here (easiest: log XXH3_64bits() once during bring-up).
static constexpr uint64_t BAR_USA_ROM_XXH3 = 0x56cfec69d7951f9fULL;   // XXH3_64 of the USA z64 (sha1 e5ab4d22…)

static std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash              = BAR_USA_ROM_XXH3,            // TODO(BAR)
        .internal_name         = "Beetle Adventure Rac",      // exact 20 bytes at ROM offset 0x20
        .game_id               = u8"bar.n64.us",             // stable id (arbitrary but fixed)
        .mod_game_id           = "bar",
        .save_type             = recomp::SaveType::None,      // BAR uses the Controller Pak (mempak), which
                                                             //   librecomp handles separately from SaveType.
        .is_enabled            = true,
        .decompression_routine = nullptr,                    // BAR code isn't compressed in the recomp output
        .has_compressed_code   = false,                      // TODO(BAR): verify vs your N64Recomp config
        .entrypoint_address    = get_entrypoint_address(),   // expected 0x80000400
        .entrypoint            = recomp_entrypoint,
    },
};

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// ----------------------------------------------------------------------------------------
// Port callback stubs. Signatures match the vendored headers; BODIES are TODO.
// ----------------------------------------------------------------------------------------

// RT64 renderer context (MANDATORY). Implemented in src/main/rt64_render_context.cpp.
std::unique_ptr<ultramodern::renderer::RendererContext>
bar_create_rt64_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode);

// Signals from rt64_render_context.cpp that gate the deferred start_game() below.
extern std::atomic<bool> g_bar_renderer_ready;   // RT64 finished setup
extern std::atomic<bool> g_bar_vi_ticked;        // renderer presented a frame (VI thread seeded a mode)

// SDL window / gfx (gfx_callbacks_t). RT64 attaches to this window's native HWND.
static SDL_Window* g_window = nullptr;

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetMainReady();
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS | SDL_INIT_GAMECONTROLLER) != 0) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_Init failed: %s\n", SDL_GetError());
    }
    return nullptr;   // gfx_data_t is unused; the window is tracked in g_window
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
    g_window = SDL_CreateWindow("Beetle Adventure Racing",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 960, 720,
        SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    if (g_window == nullptr) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_CreateWindow failed: %s\n", SDL_GetError());
        return {};
    }
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    if (SDL_GetWindowWMInfo(g_window, &wm_info) != SDL_TRUE) {
        std::fprintf(stderr, "[BeetleRecomp] SDL_GetWindowWMInfo failed: %s\n", SDL_GetError());
        return {};
    }
    // create_window runs on the same (main) thread that pumps update_gfx below, so the
    // window's owning thread id is this thread.
    return ultramodern::renderer::WindowHandle{ wm_info.info.win.window, GetCurrentThreadId() };
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        if (event.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }
}

// Audio (audio_callbacks_t). TODO(BAR): SDL audio device + sample ring buffer.
static void queue_samples(int16_t* /*samples*/, size_t /*count*/) {}
static size_t get_frames_remaining() { return 0; }
static void set_frequency(uint32_t /*freq*/) {}

// Input (input::callbacks_t). Minimal: report controller 1 as connected with a neutral state so the
// game gets past its "no controller" check (uvShowNoController). TODO(BAR): real SDL controller /
// keyboard mapping -> N64 buttons + analog stick.
static void input_poll() {}

static bool input_get(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (controller_num != 0) {
        return false;   // only port 1 is "connected" for now
    }
    if (buttons != nullptr) *buttons = 0;   // nothing pressed
    if (x != nullptr)       *x = 0.0f;      // stick centered
    if (y != nullptr)       *y = 0.0f;
    return true;
}

static void input_set_rumble(int /*controller_num*/, bool /*rumble*/) {}

static ultramodern::input::connected_device_info_t input_get_device_info(int controller_num) {
    using namespace ultramodern::input;
    if (controller_num == 0) {
        return connected_device_info_t{ Device::Controller, Pak::None };
    }
    return connected_device_info_t{ Device::None, Pak::None };
}

// Error handling (error_handling::callbacks_t).
static void message_box(const char* msg) { std::fprintf(stderr, "[BeetleRecomp] %s\n", msg); }

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    // TODO(BAR, optional): Win32 executable preload + timeBeginPeriod(1) for smoother frame times
    //                      (see Zelda's main.cpp). Omitted from this boot draft.

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        message_box(("Invalid version string: " + version_string).c_str());
        return EXIT_FAILURE;
    }

    // Config/save directory. TODO(BAR): use a proper per-user app folder, not cwd.
    recomp::register_config_path(std::filesystem::current_path());

    // Teach librecomp about BAR (hash / entrypoint / save type).
    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // Wire the generated section/overlay tables so BAR's ~130 relocatable modules resolve at runtime.
    bar_register_overlays();
    // TODO(BAR): bar::register_patches(); once patches exist.

    // ---- Pick + validate the ROM, then start the game (no menu UI yet) ----
    // The game thread blocks in wait_for_game_started() until start_game() runs; with no UI to
    // pick a ROM, we do it here. create_render_context() runs inside preinit *before*
    // wait_for_game_started(), so starting the game now does not race renderer init.
    std::filesystem::path rom_path = (argc > 1)
        ? std::filesystem::path(argv[1])
        : std::filesystem::path("C:/Users/Bryan/Downloads/Beetle Adventure Racing (USA).z64"); // TODO(BAR): real ROM picker

    std::u8string game_id = supported_games[0].game_id;
    recomp::RomValidationError rom_err = recomp::select_rom(rom_path, game_id);
    if (rom_err != recomp::RomValidationError::Good) {
        message_box(("Could not load ROM \"" + rom_path.string() + "\" (validation error "
                     + std::to_string(static_cast<int>(rom_err)) + ")").c_str());
        return EXIT_FAILURE;
    }
    // Start the game once the renderer is up. The VI thread only seeds a dummy OSViMode while
    // !is_game_started() (ultramodern events.cpp); starting before its first tick makes update_vi()
    // dereference a null mode. recomp::start() below blocks running the event loop, so defer this to
    // a detached thread that waits for the renderer-ready signal plus a margin for the first VI tick.
    std::thread([game_id]() {
        // Wait until the renderer has presented at least one frame (g_bar_vi_ticked), which means the
        // VI thread has ticked and seeded a dummy OSViMode. Starting before that races the VI thread
        // into a null-mode deref. Cap the wait (~5s) so we never hang if presentation stalls.
        for (int i = 0; i < 500 && !g_bar_vi_ticked.load(); i++) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
        recomp::start_game(game_id);
    }).detach();

    // ---- Assemble callbacks (field names verified against the vendored headers) ----
    recomp::rsp::callbacks_t rsp_callbacks{};                  // MANDATORY
    rsp_callbacks.get_rsp_microcode = get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};   // MANDATORY
    renderer_callbacks.create_render_context = bar_create_rt64_render_context;

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input = input_poll;
    input_callbacks.get_input  = input_get;
    input_callbacks.set_rumble = input_set_rumble;
    input_callbacks.get_connected_device_info = input_get_device_info;

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    recomp::Configuration config{};
    config.project_version          = project_version;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;
    // config.window_handle / events_callbacks / message_queue_control: defaults are fine for now.

    // Blocks until the game exits.
    recomp::start(config);
    return EXIT_SUCCESS;
}
